version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test1234
      POSTGRES_USER: test
      POSTGRES_DB: order-history
    ports:
      - 5432:5432
